name: Build LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout latex-listings-powershell
        run: git clone https://github.com/rmainer/latex-listings-powershell

      - name: Compile LaTeX document
        run: |
          pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf praksem.tex || true
          bibtex praksem || true
          pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf praksem.tex || true
          pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf praksem.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Semesterbericht-PDF
          path: praksem.pdf
