name: Build LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout latex-listings-powershell
        run: git clone https://github.com/rmainer/latex-listings-powershell

      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -file-line-error -interaction=nonstopmode -synctex=1 praksem.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Semesterbericht-PDF
          path: praksem.pdf
