name: Build LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        root_file: praksem.tex
        working_directory: ./
        compiler: pdflatex
        args: -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: Semesterbericht-PDF
        path: projects/praxissemester/praksem.pdf
